part 1 with dummy forecast list
TechnoStudyMobile/US_Batch1120_Homeworks pull request #22
Opened 2021-02-16 22:12 UTC by Muharrem-sdet

part 1 with recycler view and live data and dummy forecast list

2021-02-22 05:23 UTC, oliver-basoglu commented on WeatherForecast/app/src/main/java/ustun/muharrem/weatherforecast/adapters/ForecastListAdapter.kt
> +        val view =
No need for new lines.

2021-02-22 05:26 UTC, oliver-basoglu requested changes

2021-02-22 05:26 UTC, oliver-basoglu commented on WeatherForecast/app/src/main/java/ustun/muharrem/weatherforecast/adapters/ForecastListAdapter.kt
> +    private fun getDateText(valid_date: String, position: Int): String {
Create another file named DateUtils. make it object (Will act as singleton) . Move this method there

2021-02-22 05:26 UTC, oliver-basoglu commented on WeatherForecast/app/src/main/java/ustun/muharrem/weatherforecast/data/Forecast.kt
> +	val data : List<Data>,
Would suggest to rename this to forecastList and the Data class into Forecast

2021-02-22 05:26 UTC, oliver-basoglu commented on WeatherForecast/app/src/main/java/ustun/muharrem/weatherforecast/views/ForecastViewModel.kt
> +        MutableLiveData()
Refactor: to upper line

2021-02-22 05:26 UTC, oliver-basoglu commented on WeatherForecast/app/src/main/java/ustun/muharrem/weatherforecast/views/ForecastViewModel.kt
> +                t.stackTrace
?

2021-02-22 07:25 UTC, Muharrem-sdet commented on WeatherForecast/app/src/main/java/ustun/muharrem/weatherforecast/views/ForecastViewModel.kt
> +        MutableLiveData()
These happen automatically when I press ctrl + alt + l for formatting my code

2021-02-22 07:28 UTC, Muharrem-sdet commented on WeatherForecast/app/src/main/java/ustun/muharrem/weatherforecast/views/ForecastViewModel.kt
> +                t.stackTrace
It is good to show some info message here to inform the end-user, like "cannot get forecast data" or something like that.

2021-02-22 07:29 UTC, Muharrem-sdet commented on WeatherForecast/app/src/main/java/ustun/muharrem/weatherforecast/adapters/ForecastListAdapter.kt
> +    private fun getDateText(valid_date: String, position: Int): String {
Done

2021-02-22 07:29 UTC, Muharrem-sdet commented on WeatherForecast/app/src/main/java/ustun/muharrem/weatherforecast/data/Forecast.kt
> +	val data : List<Data>,
Done

2021-02-22 23:50 UTC, Kryvovyaz commented on WeatherForecast/app/src/main/java/ustun/muharrem/weatherforecast/adapters/ForecastListAdapter.kt
> +    private fun getDateText(valid_date: String, position: Int): String {
I like this method

2021-02-23 05:11 UTC, oliver-basoglu commented on WeatherForecast/app/src/main/java/ustun/muharrem/weatherforecast/adapters/ForecastListAdapter.kt
> +    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RecyclerView.ViewHolder {
Great job.

2021-02-23 05:11 UTC, oliver-basoglu commented on WeatherForecast/app/src/main/java/ustun/muharrem/weatherforecast/adapters/ForecastListAdapter.kt
> +                    high_temp_forecast_item_view.text =
If you could move these methods to individual ViewHolder by creating a method named bind(), would be perfect :)

2021-03-01 03:21 UTC, Kryvovyaz commented on WeatherForecast/app/src/main/java/ustun/muharrem/weatherforecast/screens/settings/SettingsFragment.kt
> +    private fun setDegreeViews() {
great

2021-03-24 03:17 UTC, closed without merging